### ISSUE TITLE
"font scaling factor" makes texts overflow

### ISSUE THREAD

**Issue by friday** [egara/buttermanager#14]
I've set my font scaling factor to 1.33 in gnome
`gsettings set org.gnome.desktop.interface text-scaling-factor 1.33`
(you can also do it with "gnome-tweaks").

Unfortunately this makes buttermanagers texts overflow.

![buttermanager-1](https://user-images.githubusercontent.com/515120/72106218-3f7f2c80-332f-11ea-913a-00157b713a9f.png)
![buttermanager-2](https://user-images.githubusercontent.com/515120/72106219-3f7f2c80-332f-11ea-8260-cc194e32efd8.png)
![buttermanager-3](https://user-images.githubusercontent.com/515120/72106220-4017c300-332f-11ea-98c7-3d2e8163898a.png)
![buttermanager-4](https://user-images.githubusercontent.com/515120/72106221-4017c300-332f-11ea-85f4-25aeb5ebbd91.png)
![buttermanager-5](https://user-images.githubusercontent.com/515120/72106225-4017c300-332f-11ea-9d99-52064bcfbd6e.png)
![buttermanager-6](https://user-images.githubusercontent.com/515120/72106228-40b05980-332f-11ea-98ca-b9188203aa01.png)

**Comment by egara** [comment]
Hi again!

Thanks for reporting! I'll take a look and see what can I do to fix this problem. I'll keep you inform.

**Comment by friday** [comment]
No hurry on my account. Just thought you'd like to know.

**Comment by egara** [comment]
Good morning @friday Finally I found time to solve this issue and I have added some minor fixes and documentation to version 1.8. Could you test it and confirm that the problem is solved, please? 

I have added auto-scaling so there shouldn't be any problem now.

Thank you very much and I hope you are well :)

**Comment by friday** [comment]
Sorry. I forgot about this, and I'm not actively using Buttermanager.

It looks more consistent now, but the default font size is very small for me.
![butter2](https://user-images.githubusercontent.com/515120/83333885-2f96c380-a2a3-11ea-91db-118d6ad1c3f3.png)

My "font scaling factor" in Gnome is 1.33
I could set `QT_SCALE_FACTOR` then open from a terminal to change the scaling though.

**Comment by egara** [comment]
Hi @friday and thank you very much for testing again! Ok, I see the default font size is small. Maybe I can add a new option in settings to set the default font size for this cases.

Thank you again for your time and your feedback! :)

**Comment by egara** [comment]
This issue has actually been solved, although a new functionality to change the default font size could be implemented in future versions. Thanks for the feedback again and for your time in tests!! :)
