### ISSUE TITLE
Incorrect usage reporting with RAID setup.

### ISSUE THREAD

**Issue by dron1885** [egara/buttermanager#21]
Currently testing ButterManager within Arch VM and reporting of used space are incorrect when system on btrfs' RAID.
![1599894661_grim](https://user-images.githubusercontent.com/45915083/92989972-d749a180-f4e0-11ea-8827-dbb2ede9dd32.png)

**Comment by egara** [comment]
Hi @dron1885 and thanks for the reporting.

I've never tested ButterManager against a RAID system. In order to calculate used space ButterManager executes **sudo btrfs filesystem usage /**. Could you try this command and attach a picture please?

Thank you very much!

**Comment by dron1885** [comment]
Output:
```
Overall:
    Device size:		  40.50GiB
    Device allocated:		   9.56GiB
    Device unallocated:		  30.94GiB
    Device missing:		     0.00B
    Used:			   7.41GiB
    Free (estimated):		  32.35GiB	(min: 16.88GiB)
    Data ratio:			      1.00
    Metadata ratio:		      2.00
    Global reserve:		  25.20MiB	(used: 0.00B)
    Multiple profiles:		        no

Data,RAID0: Size:8.00GiB, Used:6.59GiB (82.34%)
   /dev/vda3	   4.00GiB
   /dev/vdb	   4.00GiB

Metadata,RAID1: Size:768.00MiB, Used:421.33MiB (54.86%)
   /dev/vda3	 768.00MiB
   /dev/vdb	 768.00MiB

System,RAID1: Size:32.00MiB, Used:16.00KiB (0.05%)
   /dev/vda3	  32.00MiB
   /dev/vdb	  32.00MiB

Unallocated:
   /dev/vda3	  15.72GiB
   /dev/vdb	  15.22GiB
```

**Comment by egara** [comment]
Hi @dron1885 

Thanks for pasting the output. I think it is fixed. If you have installed the application via AUR, you can do a system upgrade (yay -Syua) for AUR packages and ButterManager version 2.0-2 will be installed.

Could you test it and tell me if everything works OK? Thank you very much!

**Comment by dron1885** [comment]
@egara New version is working as expected, thanks!

**Comment by egara** [comment]
Thanks to you for the feedback!! :D
