### ISSUE TITLE
Does not create snapshots automatically

### ISSUE THREAD

**Issue by haivala** [egara/buttermanager#23]
> Creating snapshots and updating GRUB entries if it is necessary... 

When I run the update in the ButterManager I can see that in the log but there is not a new snapshot if I don't make it manually and when I make one it is added to grub menu.
I'm just wondering have I done something wrong or is this how it should work?

Is there an easy way to trigger the automatic snapshot creation when I run the system update from the command line?

**Comment by egara** [comment]
Hi @haivala thanks for reporting.

Please, check the following:

1.- Do you have subvolumes added in Settings tab? You will need at least one subvolume added here in order to ButterManager create the snapshot automatically.
2.- In Settings tab: Snapshots to keep must be 1 or greater.
3.- In Settings tab: You need to check Boot the system from GRUB using snapshots.
4.- In Settings tab: If you have checked "Check updates at startup", a new window will pop up when ButterManager runs and detects pending updates. Be sure that you are clicking on the button "Upgrade with snapshots".
4.- What distro are you using?

Thanks!

**Comment by haivala** [comment]
![image](https://user-images.githubusercontent.com/3918267/102871540-3a839200-4447-11eb-98b8-6d55955f0471.png)

1. yes
2. yes
3. yes
4. I haven't checked that, Where the "Upgrade with snapshots"- button should be?
5. Arch

**Comment by haivala** [comment]
![image](https://user-images.githubusercontent.com/3918267/102872686-bc27ef80-4448-11eb-8c82-6330708b10e6.png)

**Comment by egara** [comment]
Ok, please, check "Check updates at startup" first. Then, close ButterManager and run it again. If there is some package that is needed to update, a new pop up window will appear. There it is the button that I tell you. Please, click on it and tell me if it works:

![Screenshot_20201222_102802](https://user-images.githubusercontent.com/13696843/102873047-e70e4580-4440-11eb-8e3a-860f3198b525.png)

**Comment by egara** [comment]
By the way, regarding to you second question

`Is there an easy way to trigger the automatic snapshot creation when I run the system update from the command line?`

No, there is no way to integrate ButterManager with pacman directly, sorry for that, but there are some packages (scripts) that can do that. You can [check some solutions here](https://www.reddit.com/r/archlinux/comments/54ni8u/arch_btrfs_snappac_grubbtrfs_snapper_amazing/)

**Comment by haivala** [comment]
I suggest that the button should be under "Other Operations" in the main tab? I think the heading is not necessary.
I have other means to check if I have updates and there is times I would like to just take a snapshot so this would be better usability.

To conclude my suggestion: remove the heading "Other Operations" and the buttons from left to right:
"Upgrade System", "Upgrade with snapshots", "Take a Snapshot", "Regenerate GRUB"
The Take a Snapshot would just open the same dialogue as the plus in the Snapshots tab.

**Comment by egara** [comment]
Ok, I get it. i think you are right. And I think that, instead of "Other operations" maybe a better title for this part of the GUI would be simply "Operations" os "Fast Actions".

By the way, did it work? Upgrading the system including snapshots run well?

**Comment by haivala** [comment]
> By the way, did it work? Upgrading the system including snapshots run well?

There has not been any updates yet, I'll let you know

**Comment by egara** [comment]
Thank you very much :)

**Comment by haivala** [comment]
It works as it should

**Comment by egara** [comment]
Ok, thanks for the feedback. 

I'll take all your suggestions and I'll check the behavior of the button "Upgrade System" as well because I think it is a little bit confusing.

I close the issue now :)

Best wishes.

**Comment by haivala** [comment]
Thank you!
