### ISSUE TITLE
'unknown': I need something more specific.

### ISSUE THREAD

**Issue by Deckweiss** [egara/buttermanager#44]
I sometimes get an error when updating with snapshots. Not every time, but about 50/50

I think it started happening after the last python version update on Arch. I have rebuild buttermanager from AUR after that update.

```
Checking for system updates.
--------

--------
Starting system upgrading process. Please wait...

--------
Creating snapshots and updating GRUB entries if it is necessary...
--------
Create a snapshot of '/mnt/defvol/_active/root/' in '/mnt/defvol/_snapshots/root-20211221-0'
Create a readonly snapshot of '/mnt/defvol/_active/home/' in '/mnt/defvol/_snapshots/home-20211221-0'
Upgrading the system. Please wait...
:: Synchronizing package databases...
 system downloading...
 world downloading...
 galaxy downloading...
 lib32 downloading...
 universe downloading...
 extra downloading...
 community downloading...
 multilib downloading...
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (11) cmake-3.22.1-3  jsoncpp-1.9.5-1  lib32-libxcrypt-4.4.27-1  libthai-0.1.29-1  libxcrypt-4.4.27-1  nodejs-17.3.0-1  openxr-1.0.20-2  python-cryptography-36.0.1-1  tcl-8.6.12-3  webkit2gtk-2.34.3-1  wine-staging-7.0rc1-1

Total Download Size:   112.43 MiB
Total Installed Size:  695.22 MiB
Net Upgrade Size:       -2.52 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 wine-staging-7.0rc1-1-x86_64 downloading...
 webkit2gtk-2.34.3-1-x86_64 downloading...
 nodejs-17.3.0-1-x86_64 downloading...
 cmake-3.22.1-3-x86_64 downloading...
 tcl-8.6.12-3-x86_64 downloading...
 python-cryptography-36.0.1-1-x86_64 downloading...
 openxr-1.0.20-2-x86_64 downloading...
 libthai-0.1.29-1-x86_64 downloading...
 jsoncpp-1.9.5-1-x86_64 downloading...
 libxcrypt-4.4.27-1-x86_64 downloading...
 lib32-libxcrypt-4.4.27-1-x86_64 downloading...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
upgrading jsoncpp...
upgrading libxcrypt...
'unknown': I need something more specific.
```

After this the program hangs. Killing it and trying to update manually says that there is already an update process running. 

Restarting results in a broken system sometimes, especially when kernel updates take place.

Anything I can provide or do to debug this issue?

**Comment by Deckweiss** [comment]
Actually, nevermind

I was using pamac to update afterwards. 

Running pacman again out of curiosity showed me that it keeps hanging up randomly.

**Comment by egara** [comment]
Hi @Deckweiss 

You are right, after the Python's upgrade to the new version, it is necessary to rebuild ButterManager. On the other hand, the pacman issue will be resolved sooner or later I guess :)

Thanks for reporting, as always!

**Comment by Deckweiss** [comment]
I figured out the issue. 

I think buttermanager starts an interactive shell and for some reason stuff from my .bashrc was interfering with it (specifically https://github.com/Deckweiss/auto-root tool)

Adding an env variable in the buttermanager desktop file to disable said tool seems to have fixed it.

**Comment by egara** [comment]
@Deckweiss nice tool!!! Very useful, thank you very much for this :)
