### ISSUE TITLE
Loaded into a snapshot, Butter doesn't work anymore

### ISSUE THREAD

**Issue by bloodhori** [egara/buttermanager#56]
I had to load into a snapshot. When i start butter it recognizes what i did and asks if i want to consolidate it as default. The cancel button doesn't work and when i click OK it just closes and nothing happens. It is on Arch.

Edit: From console i have some additional information.

> buttermanager
```
btrfs subvolume snapshot: exactly 2 arguments expected, 1 given
btrfs subvolume show: exactly 1 argument expected, 0 given
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/buttermanager/buttermanager/window/windows.py", line 269, in consolidate
    commandline_output = subprocess.check_output(command, shell=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo btrfs subvolume show ']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/buttermanager/buttermanager/window/windows.py", line 272, in consolidate
    str(called_process_error_exception.reason))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CalledProcessError' object has no attribute 'reason'
Aborted (core dumped)
```

**Comment by egara** [comment]
Hi @bloodhori and thank you very much for your feedback. I've been testing the cancel button and you are right. It is not working now (I suspect it is something to do with QT6. Are you in KDE Plasma 6?) I have to do some additional tests related to the consolidation process and I'll come back to you.

Thanks again!

**Comment by egara** [comment]
Hi again @bloodhori 

I have been testing this problem and I cannot reproduce it in my own computer (it is Arch too). Everything is working fine. However, I have solved the problem with the Cancel button. Version 2.5.2 has just been released so it should work now.

If there is some more information about this bug or a way to reproduce it, please let me know.

Thanks!
